#pragma once
#include <vector>
#include "PlayButton.h"
#include "StopButton.h"
#include "ForwardButton.h"
#include "BackwardButton.h"
#include "SaveButton.h"
#include "FileReader.h"
#include "Game.h"
#include "RLEFileText.h"